### ISSUE TITLE
grunt-contrib-bump

### ISSUE THREAD

**Issue by vladikoff** [mikaelkaron/grunt-semver#3]
Hey @mikaelkaron !
There's now going to be a contrib plugin for semver. ( https://github.com/gruntjs/grunt-contrib-bump )
Would you like to merge the efforts into a single project?

See discussion at:
https://github.com/gruntjs/grunt-contrib-bump/issues/1

**Comment by patrick-motard** [comment]
Both grunt-semver and grunt-contrib-bump look to do what I need. Grunt-semver has not been updated to support Grunt >= 1.0.0, And grunt-contrib-bump has a giant "DEPRECATED" sign on it. Looks like nothing was done to merge these. Which library should I submit a PR to to update dependencies to support Grunt 1.0.0?

Also, @vladikoff, why is grunt-contrib-bump deprecated? Did another contrib package succeed it?

**Comment by patrick-motard** [comment]
Looks like there is an [open PR](https://github.com/mikaelkaron/grunt-semver/pull/6) for supporting Grunt 1.0.0. Could that be merged in @mikaelkaron ?

**Comment by mikaelkaron** [comment]
Merged. Let's make a release
